//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FEIClient.FEIService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ViewStudentInfo", Namespace="http://schemas.datacontract.org/2004/07/Domain")]
    [System.SerializableAttribute()]
    public partial class ViewStudentInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idCareerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idStudentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idTutorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fullName {
            get {
                return this.fullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.fullNameField, value) != true)) {
                    this.fullNameField = value;
                    this.RaisePropertyChanged("fullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idCareer {
            get {
                return this.idCareerField;
            }
            set {
                if ((this.idCareerField.Equals(value) != true)) {
                    this.idCareerField = value;
                    this.RaisePropertyChanged("idCareer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idStudent {
            get {
                return this.idStudentField;
            }
            set {
                if ((object.ReferenceEquals(this.idStudentField, value) != true)) {
                    this.idStudentField = value;
                    this.RaisePropertyChanged("idStudent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idTutor {
            get {
                return this.idTutorField;
            }
            set {
                if ((this.idTutorField.Equals(value) != true)) {
                    this.idTutorField = value;
                    this.RaisePropertyChanged("idTutor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idUser {
            get {
                return this.idUserField;
            }
            set {
                if ((this.idUserField.Equals(value) != true)) {
                    this.idUserField = value;
                    this.RaisePropertyChanged("idUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FEIService.IViewStudentInfo")]
    public interface IViewStudentInfo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IViewStudentInfo/LogIn", ReplyAction="http://tempuri.org/IViewStudentInfo/LogInResponse")]
        FEIClient.FEIService.ViewStudentInfo LogIn(string studentId, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IViewStudentInfo/LogIn", ReplyAction="http://tempuri.org/IViewStudentInfo/LogInResponse")]
        System.Threading.Tasks.Task<FEIClient.FEIService.ViewStudentInfo> LogInAsync(string studentId, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IViewStudentInfoChannel : FEIClient.FEIService.IViewStudentInfo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ViewStudentInfoClient : System.ServiceModel.ClientBase<FEIClient.FEIService.IViewStudentInfo>, FEIClient.FEIService.IViewStudentInfo {
        
        public ViewStudentInfoClient() {
        }
        
        public ViewStudentInfoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ViewStudentInfoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ViewStudentInfoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ViewStudentInfoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FEIClient.FEIService.ViewStudentInfo LogIn(string studentId, string password) {
            return base.Channel.LogIn(studentId, password);
        }
        
        public System.Threading.Tasks.Task<FEIClient.FEIService.ViewStudentInfo> LogInAsync(string studentId, string password) {
            return base.Channel.LogInAsync(studentId, password);
        }
    }
}
