//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FEIClient.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FEIClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, llene todos los campos.
        /// </summary>
        internal static string MessageBox_Error_EmptyFields {
            get {
                return ResourceManager.GetString("MessageBox_Error_EmptyFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un error mientras se registraba su usuario, intentelo más tarde.
        /// </summary>
        internal static string MessageBox_Error_RegisterError {
            get {
                return ResourceManager.GetString("MessageBox_Error_RegisterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El servicio no se encuentra disponible.
        /// </summary>
        internal static string MessageBox_Error_ServiceException {
            get {
                return ResourceManager.GetString("MessageBox_Error_ServiceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya es tu turno, por favor pasa con la secretaria.
        /// </summary>
        internal static string MessageBox_Notification_YourTurn {
            get {
                return ResourceManager.GetString("MessageBox_Notification_YourTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eres el proximo en pasar.
        /// </summary>
        internal static string MessageBox_Notification_YourTurnNext {
            get {
                return ResourceManager.GetString("MessageBox_Notification_YourTurnNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu turno fue cancelado.
        /// </summary>
        internal static string MessageBox_Notification_YourTurnWasCanceled {
            get {
                return ResourceManager.GetString("MessageBox_Notification_YourTurnWasCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Credeciales incorrectas.
        /// </summary>
        internal static string MessageBox_SignIn_IncorrectCredentials {
            get {
                return ResourceManager.GetString("MessageBox_SignIn_IncorrectCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, ingresa una matricula valida.
        /// </summary>
        internal static string MessageBox_SingUp_BadMatricula {
            get {
                return ResourceManager.GetString("MessageBox_SingUp_BadMatricula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, ingrese una contraseña que contenga mínimo 8 caracteres, al menos un numero y
        /// un símbolo.
        /// </summary>
        internal static string MessageBox_SingUp_BadPassword {
            get {
                return ResourceManager.GetString("MessageBox_SingUp_BadPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El registro se ha completado con exito.
        /// </summary>
        internal static string MessageBox_Success_RegisterSucessfull {
            get {
                return ResourceManager.GetString("MessageBox_Success_RegisterSucessfull", resourceCulture);
            }
        }
    }
}
